name: Daily Emoji Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Every day at 08:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run scrape script
        run: npm run scrape

      - name: Commit & push data files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: add daily emojis file"
          file_pattern: data/*.json
          branch: ${{ github.ref_name }}
